freebsd_instance:
  image_family: freebsd-12-1

task:
  install_script: pkg install -y cmake
  script: mkdir cmake-build-debug && cd cmake-build-debug && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .
