FROM alpine

COPY . /osbuild

WORKDIR /osbuild

RUN apk add --no-cache gcc cmake make libc-dev && \
    mkdir 'cmake-build-docker-debug' && \
    cd '/osbuild/cmake-build-docker-debug' && \
    cmake -DCMAKE_BUILD_TYPE=Debug .. && \
    cmake --build "$PWD" && ls -l && chmod +x ./osbuild

CMD /osbuild/cmake-build-docker-debug/osbuild
