FROM debian

COPY . /osbuild

WORKDIR /osbuild

RUN apt-get update -qq && \
    apt-get install -y gcc cmake make libc-dev && \
    mkdir 'cmake-build-docker-debug' && \
    cd '/osbuild/cmake-build-docker-debug' && \
    cmake -DCMAKE_BUILD_TYPE='Debug' .. && \
    cmake --build "$PWD" && chmod +x ./osbuild

CMD /osbuild/cmake-build-docker-debug/osbuild
